 spring:
  datasource:
    url: jdbc:h2:mem:viswa
    driverClassName: org.h2.Driver
    username: viswa
    password: welcome
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

 server:
  port: 5678